#FROM debian:bullseye-slim
FROM debian:stretch-slim
LABEL description="Magiclantern qemu-eos builder"

# clean is not needed with official Debian images,
# RUN apt-get clean

# update is required since we later install packages,
# and Debian images ship with empty apt cache
RUN apt-get update && \
apt-get install -qy --no-install-recommends \
build-essential \
python3 \
wget \
unzip \
pkg-config \
libgtk-3-dev \
flex \
bison \
zip \
&& rm -rf /var/lib/apt/lists/*

# create user for building
RUN useradd -ms /bin/bash ml_builder
WORKDIR /home/ml_builder
USER ml_builder

# copy qemu source from host to container
COPY qemu_src_4.tar qemu_src.tar
RUN mkdir qemu-eos-build && \
cd qemu-eos-build && \
tar -xf ../qemu_src.tar

# build qemu
ENV NUM_CPUS=16
RUN cd qemu-eos-build && \
./configure --target-list=arm-softmmu --enable-plugins --disable-docs --enable-vnc --enable-gtk && \
make -j $NUM_CPUS && \
make plugins && \
cp tests/plugin/libmagiclantern.so arm-softmmu/plugins/

# zip runtime for copy to host
RUN zip qemu_4.zip -r qemu-eos-build/arm-softmmu
